CREATE TABLE autor (
  id_autor BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  email  VARCHAR (50) NOT NULL,
  nome  VARCHAR (50) NOT NULL,
  senha  VARCHAR (50) NOT NULL,

) ENGINE=InnoDB DEFAULT CHARSET=utf8;